version: "3.7"
volumes:
  database:
services:
    db:
        image: mysql:latest
       
        container_name: squad5-mysql
        security_opt:
            - seccomp:unconfined
        ports:
            - 3306:3306
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        
        environment:
            - MYSQL_ROOT_PASSWORD=squad5
            - MYSQL_DATABASE=squad5
            - MYSQL_USER=squad5
            - MYSQL_PASSWORD=squad5
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci', '--skip-character-set-client-handshake']
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: squad5-phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        links:
            - "db"
        ports:
            - 8080:80
        volumes:
            - /sessions
    app:
        build: .
        container_name: squad5
        volumes:
            - .:/var/www/html
        depends_on:
            - "db"
            - "phpmyadmin"
        ports:
            - 80:80
            - 443:443